# Generated by Django 5.2.13 on 2026-04-28 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nom')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='Slug')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='Icône')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
            ],
            options={
                'verbose_name': 'Catégorie',
                'verbose_name_plural': 'Catégories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='Slug')),
                ('description_short', models.CharField(max_length=300, verbose_name='Description courte')),
                ('description_long', models.TextField(verbose_name='Description longue (Markdown)')),
                ('project_type', models.CharField(choices=[('academic', 'Académique'), ('personal', 'Personnel')], max_length=20, verbose_name='Type de projet')),
                ('github_url', models.URLField(blank=True, verbose_name='URL GitHub')),
                ('demo_url', models.URLField(blank=True, verbose_name='URL Démo')),
                ('report_pdf', models.FileField(blank=True, upload_to='reports/', verbose_name='Rapport PDF')),
                ('thumbnail', models.ImageField(blank=True, upload_to='thumbnails/', verbose_name='Miniature')),
                ('tech_stack', models.JSONField(default=list, verbose_name='Stack technique')),
                ('date_realized', models.DateField(verbose_name='Date de réalisation')),
                ('is_featured', models.BooleanField(default=False, verbose_name='En vedette')),
                ('is_published', models.BooleanField(default=True, verbose_name='Publié')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='projects.category', verbose_name='Catégorie')),
            ],
            options={
                'verbose_name': 'Projet',
                'verbose_name_plural': 'Projets',
                'ordering': ['-is_featured', 'order', '-date_realized'],
            },
        ),
    ]
