# Generated by Django 5.2.13 on 2026-04-28 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom')),
                ('issuer', models.CharField(max_length=100, verbose_name='Organisme émetteur')),
                ('logo', models.ImageField(blank=True, upload_to='cert_logos/', verbose_name='Logo')),
                ('credential_url', models.URLField(blank=True, verbose_name='Lien Credly / Coursera')),
                ('date_obtained', models.DateField(verbose_name="Date d'obtention")),
                ('is_featured', models.BooleanField(default=False, verbose_name='En vedette')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
            ],
            options={
                'verbose_name': 'Certification',
                'verbose_name_plural': 'Certifications',
                'ordering': ['-is_featured', 'order', '-date_obtained'],
            },
        ),
    ]
