# Generated by Django 5.2.13 on 2026-04-28 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='certification',
            name='logo_url',
            field=models.URLField(blank=True, help_text='URL vers le logo officiel (optionnel)', verbose_name='URL logo externe'),
        ),
    ]
